### ISSUE TITLE
Changes should only be applied when hit the update/save button

### ISSUE THREAD

**Issue by mathewriver** [ultimatemember/ultimatemember#777] opened 2021-03-12 08:06 UTC
I'm having one big issue with the plugin when editing the form:

Whatever change I make gets automatically updated. It would be better to have an option to only save changes when we click the Update button.

I'm saying this because I accidently deleted a field and couldn't recover it. Also, I accidently changed the amount of columns.

**Comment by nikitasinelnikov** [comment] 2021-03-12 13:26
Closed as an exact duplicate of https://github.com/ultimatemember/ultimatemember/issues/706

**Closed by nikitasinelnikov** 2021-03-12 13:26 UTC

**Comment by mathewriver** [comment] 2021-03-12 17:30
@nikitasinelnikov I didn't know someone already pointed this problem. This is really a serious issue.
