### ISSUE TITLE
Results Text & Single Result Text default value back every time we edit a Member Directory

### ISSUE THREAD

**Issue by FlyThePlanet** [ultimatemember/ultimatemember#607] opened 2019-11-22 23:46 UTC
**Describe the bug**
If we deleted the values in the "Results Text" & "Single Result Text" fields on a Member Directory form, save and edit the same Member Directory, the "Results Text" & "Single Result Text" fields are back with their default value while in reality those 2 fields are empty in the record.

**Expected behavior**
As those 2 fields have been emptied, the form saved, I expect the next time I edit this Member Directory to have those 2 fields empty.

**To Reproduce**
1. Go to WP admin > Ultimate Member > Member Directories > Members record > Edit
2. Scroll down to the "Results Text" & "Single Result Text" fields > empty those 2 fields
3. Scroll up and click on [Update]
4. Scroll down to the "Results Text" & "Single Result Text" fields > you will immediately see they are filled in again with their default values, even though the record has been saved with no values for those 2 fields

But...
1/ the next time you'll come back and edit this record, you'll have no clue if those 2 fields are empty or not in the DB record
2/ if you just came there to adjust a setting on the top of the form, you'll never notice that those 2 fields have been filled in again and you'll save the form with those 2 settings modified, while it was not your will.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [x] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
<details>
WP 5.3
PHP 7.2
UM 2.1.1
</details>

**Comment by nikitasinelnikov** [comment] 2019-11-26 15:31
Hi @FlyThePlanet 

This issue will be fixed in the next 2.1.2 version.

Thanks for your feedback!

**Comment by FlyThePlanet** [comment] 2019-11-26 16:32
Thanks! 👍

**Comment by nikitasinelnikov** [comment] 2019-11-26 17:10
You could check the issue is resolved here

**Comment by FlyThePlanet** [comment] 2019-11-26 17:36
I found no difference. No fix in the 2.1.2 RC1.

**Comment by nikitasinelnikov** [comment] 2019-11-26 21:02
Could you try to flush all cache (server, plugins, browser) and try again? I don't see these texts at my dev installation until search or filtering. https://ultimate.g-photo.com.ua/members/

**Comment by FlyThePlanet** [comment] 2019-11-26 21:24
Nope, same. No change.

It just so happen that I've re-installed my computer 1 week ago, re-installed EasyPHP and used it for the first time. So no server cache.
Then the installation is also brand new : new WP 5.3 & UM 2.1.2 RC1. So no plug-in cache.
I've cleared the browser cache as well.
I only have the 3 WP themes, Twenty Twenty activated and no other plug-in installed. I think I can't be cleaner.

**Comment by nikitasinelnikov** [comment] 2019-11-26 22:01
Do you use custom templates in your theme? Please make sure that "wp-content/themes/{theme_slug}/ultimate-member" folder is empty

**Comment by nikitasinelnikov** [comment] 2019-11-26 22:11
Hi @FlyThePlanet 

Sorry, just there was fixed another issue with these texts at the frontend. I'll add the fix in a moment

Thanks!

**Comment by nikitasinelnikov** [comment] 2019-11-26 22:23
Please re-download rc.1 version for the fix from here 
https://github.com/ultimatemember/ultimatemember/releases/tag/2.1.2-rc.1

**Comment by FlyThePlanet** [comment] 2019-11-27 09:33
Ok, this time this issue is fixed.

However I'm not sure your help in the field is a good idea.
At the moment this text is still too dark, it's very easy to confuse with a normal value in black, it tricks the user and we can also manage to select the text which also tricks the user (start your selection (click) just above the field and go down inside the field)...

![image](https://user-images.githubusercontent.com/39710808/69711267-0da86280-1101-11ea-99e7-9a0249414383.png)

I would suggest any of the following:
- Make this help much lighter grey
- Move the help after the field name: "Results Text ({total_users} Members)"
- Move the help below the field like for those WP code fields...
![image](https://user-images.githubusercontent.com/39710808/69711152-dafe6a00-1100-11ea-8db0-c0a31834e868.png)

**Comment by nikitasinelnikov** [comment] 2019-11-27 22:32
Hi @FlyThePlanet 

There is displaying filled and empty fields in the latest version:

https://www.screencast.com/t/5yxmZt0kKN

Regards

**Comment by FlyThePlanet** [comment] 2019-11-27 22:42
I think it's better like that.
Thanks! 👍

**Closed** 2019-11-27 22:54 UTC
