### ISSUE TITLE
Ultimate member plugin load file over http instead of https

### ISSUE THREAD

**Issue by petrk94** [ultimatemember/ultimatemember#272] opened 2017-05-19 20:29 UTC
Hello,
I have an issue in the Ultimate Member Plugin for Wordpress.
The Website is running on https, but the Plugin load a image file over http.
See Chrome Developer tools Console log:

Mixed Content: The page at 'https://xxx.net/wp-admin/admin.php?page=ultimatemember' was loaded over HTTPS, but requested an insecure image 'http://xxx.net/wp-content/plugins/ultimate-member/assets/img/default_avatar.jpg'. This content should also be served over HTTPS.

Can someone tell me what is the issue?
Wordpress is correctly set on https, but why this one file is getting loaded over http ?
Thanks

**Comment by champsupertramp** [comment] 2017-07-18 14:54
Hi,

Are you still encountering this issue with the latest version 1.3.87?

Regards,

**Comment by petrk94** [comment] 2017-07-18 17:13
@champsupertramp 
yes, I have the lastest version installed, but the issue is the same.

**Comment by champsupertramp** [comment] 2017-07-19 07:56
Hi @petrk94 - do you have any UM extensions installed on your site?

**Comment by petrk94** [comment] 2017-07-19 12:50
Hi @champsupertramp we use User Role Editor Version 4.35.2 | By Vladimir Garagulya

**Comment by jsilverYVR** [comment] 2017-09-10 22:06
I'm also having this problem.  I don't have any UM extensions installed.  I recently moved to a new host and installed SSL after the move.  I've been able to get rid rid of http:// on other src attributes but not on the UM images.

**Comment by jsilverYVR** [comment] 2017-09-14 22:20
Any solution to this problem?  It's affecting every post on which the site has received comments.

**Comment by PBTR** [comment] 2017-10-02 23:28
I am also having this issue, i use WC extension as well

**Comment by RobertOosterloo** [comment] 2017-11-03 11:19
Hi @petrk94 @jsilverYVR @PBTR @champsupertramp ,

I had the same issue. I sort of fixed the problem by changing the default avatar by using gravatar.

Step 1) Go to your https://YOURDOMAIN.com/wp-admin/
Step 2) Go to Ultimate Member -> Settings
Step 3) Go to User and scroll down to: Use Gravatars?
Step 4) Mark Yes en put it on Mystery Man.
Step 5) Save and it should be fixed
Step 6) (Optional) Clear Cache

Hope this helps

**Comment by jsilverYVR** [comment] 2017-11-03 20:44
@RobertOosterloo thank you! Using the gravatar totally worked.

**Comment by G-ITMS1972** [comment] 2018-01-24 12:27
Hi Everyone, 

I am having the same issue and should be grateful if someone could help me please. 

I have tried the solution suggested above but it's not working in my situation. In fact, in my case, I have cloned the Production domain to Test and the issue is happening on the Test website since. 


Error Message: Mixed Content: The page at 'https://test.network.g-itms.net/' was loaded over HTTPS, but requested an insecure image 'http://network.g-itms.net/wp-content/plugins/ultimate-member/assets/img/default_avatar.jpg'. This content should also be served over HTTPS.


"Use Gravatars" was already set to "Yes" and "User Gravatar builtin image" was already set to "Mystery Man". I've tried to reset the values and set them back to the values suggested by @RobertOosterloo but the issue is still happening.

From Chrome sources I can see that the following lines of code are loading the http image:

*******************************************
<div class="um-modal-body">
	<ul class="um-avatar-suggestions-list">
		<li id="um_avatar_list_item_default">
			<a href="#" data-id="default"><img src="http://network.g-itms.net/wp-content/plugins/ultimate-member/assets/img/default_avatar.jpg" /></a>
			<div class="um-avatar-type">Default</div>
		</li>
	</ul>
</div>

...

if ( 'default' === avatar_id ) {
	jQuery( '.um-avatar-uploaded,.um-avatar-suggested, .um-profile-photo-img .avatar' ).attr( 'src', 'http://network.g-itms.net/wp-content/plugins/ultimate-member/assets/img/default_avatar.jpg' );
}

*******************************************


I have tried to see if the url of the http image was a configuration setting from a table but in vain. I could see metadata pointing to the Production domain and have updated the URLs on the test database accordingly to point to the Test domain but the issue persists.

I should be grateful if someone could kindly help me please.

Thank you very much

@G-ITMS1972

**Comment by G-ITMS1972** [comment] 2018-01-24 12:32
Please find enclosed screenshot.
![screenshot - error message](https://user-images.githubusercontent.com/35766029/35332343-1be58cae-0124-11e8-8f9a-10e7c91c4d53.PNG)

**Comment by RobertOosterloo** [comment] 2018-01-24 13:20
Hi @G-ITMS1972 ,

Have u tried to emtpy your wordpress cache and browser cache? And did a hard refresh?

**Comment by G-ITMS1972** [comment] 2018-01-24 18:03
Hi @RobertOosterloo,

Thank you for trying to help.

I have cleared the browser cache and did a hard refresh without success. I have also restarted the website, and that did not fix the issue either.

I'm not sure what else to try.

**Comment by G-ITMS1972** [comment] 2018-01-26 02:36
Hi Everyone

I have resynchronized the Test system from Prod and the issue has been resolved by miracle.

SSL is now fully active on the Test website.

G-ITMS1972

**Comment by wedide** [comment] 2018-02-21 23:16
Hi Together,

it only happens when I'm logged in. It's the tiny user icon in the upper right corner,
It is absent when I am logged off - no problems in that case.

**Comment by 2shovelz** [comment] 2018-05-13 07:30
I downloaded the avatar
went into ultimate member-settings-profile and uploaded with a new name for the default profile pic.

**Comment by annfp16** [comment] 2018-05-22 12:26
Hello,
I have an issue in the Ultimate Member Plugin for Wordpress.

um-api/route/um!core!Files/ajax_image_upload/6e039b240a 404 (Not Found)
![screenshot from 2018-05-22 17 55 53](https://user-images.githubusercontent.com/18133212/40362179-6b6bc744-5de9-11e8-93f0-36222b4e4423.png)

**Comment by lexzz** [comment] 2018-07-10 12:55
Im having the same issue as @annfp16 
Someone already found a solution?

**Comment by lexzz** [comment] 2018-08-10 11:37
The upload problem seems to be fixed. But after uploading the window to crop the picture hangs. The crop function doesn't work properly

**Comment by champsupertramp** [comment] 2018-08-10 11:45
Hi @lexzz, 

Did you try the latest version 2.0.22?

**Comment by lexzz** [comment] 2018-08-10 12:01
Hi @champsupertramp 
Just installed the latest version. 
When I check my console I see the following error https://www.******.com/um-api/route/um!core!Files/ajax_resize_image/e4b9341143 not found (404)

The uploading seems to work, when I close the upload window and refresh the page, the uncropped picture is visible.

**Comment by lexzz** [comment] 2018-08-13 09:49
Just found the problem! 
The problem seemed to be the permalink of the WordPress installation
The way it was configured didn't work with ultimatemember

**Closed** 2018-08-17 20:19 UTC
Labels: 1.3.x, Needs confirmation

**Comment by SkySlab** [comment] 2018-10-26 00:41
I'm getting an issue similar in Chrome - no profile image and not able to view the profile at all on a page.  What did you set your permalinks to?

**Comment by lexzz** [comment] 2018-10-26 10:40
Hi SkySlab,
I'm using the following permalink setting: /%category%/%postname%/

Hope it will help you
lexzz
