### ISSUE TITLE
Enfold theme Mega Menu option disappears with UM activated

### ISSUE THREAD

**Issue by uma-mantonio** [ultimatemember/ultimatemember#328] opened 2017-10-04 11:59 UTC
Ultimate Member **deactivated**
![um_deactivated](https://user-images.githubusercontent.com/7466900/31174550-e04e5696-a8d9-11e7-9b04-0b0c8f12eda2.jpg)

Ultimate Member **activated**
![um_activated](https://user-images.githubusercontent.com/7466900/31174565-edda3bf4-a8d9-11e7-9723-0af61db38741.jpg)

**Comment by denisbaranov** [comment] 2017-10-19 14:51
Hi,

Please upgrade your local repo. We have added the latest changes day ago.

Thanks!

**Comment by uma-mantonio** [comment] 2017-10-26 17:39
That's the same version I'm using as there has been no update to the Wordpress plugin yet. If this issue has been fixed then please update the Wordpress plugin.

**Comment by n3dwards** [comment] 2017-10-26 17:48
@uma-mantonio, I'm not seeing any indication by the developers that this issue has been resolved. The only places I've seen anyone respond with suggestions (here and in the support forum: https://wordpress.org/support/topic/enfold-theme-mega-menu-option-problem/) they just say to update to the latest version.

That's clearly not solving the problem though, so this issue should really be reopened, it seems. No?

**Comment by uma-mantonio** [comment] 2017-10-26 17:51
I totally agree

**Comment by n3dwards** [comment] 2017-10-26 17:54
Ah, sorry. I missed the reference to the commit that fixes it for the Enfold theme. It just appears that it's not into a tagged release yet, and certainly not on the WP plugin directory either.

I'll have to pull master and see if that fixes the problem for me, but it should for you @uma-mantonio

**Comment by uma-mantonio** [comment] 2017-10-26 17:58
Yeah great, we can update the plugin, but can the average user? Why isn't there a new release for this fix like 1.3.89 or something?!?!?!?!?!?

**Comment by n3dwards** [comment] 2017-10-26 18:02
Just a result of their development process, likely. Devs don't like to create a new official release for each bugfix. That's just a lot of overhead and causes users to have to update too many times.

If you update the plugin files manually (which is usually not advisable), it shouldn't cause issues when you update it via the WP admin later, since it will overwrite your files, but should include the fix anyway.

**Comment by n3dwards** [comment] 2017-11-01 15:35
@denisbaranov

Finally got around to installing this on my site. The version in WP is labelled as 2.0-beta1 and I can confirm that the issue is not resolved, at least with the Newspaper 8 theme that I am using. I would hate to have to use an entirely different plugin to manage my users because of this odd interaction.

@uma-mantonio, have you tried this yet?

**Comment by uma-mantonio** [comment] 2017-11-10 17:35
No I have not tried this yet and it's very disappointing that the plugin authors seem to not care at all...

**Comment by nikitasinelnikov** [comment] 2017-11-12 19:05
Hi @uma-mantonio @n3dwards so sorry for delay and disappointing and thanks for your feedback. 

~3 weeks ago @denisbaranov created testing environment with installed "Enfold" theme. Made some fixes and have tested the latest 2.0-beta1 with "Enfold" theme before making "close" this issue. 

Maybe the test environment does not have 100% similarity with your site @uma-mantonio , so if you can check how the 2.0-beta1 version works for you, you can help us figure out how the problem was resolved (you can download it here https://github.com/ultimatemember/ultimatemember/archive/release/2.0.zip)

We working hard for UM2.0 release now, which will be fully released in few weeks and will add the fix, if it still does not work as soon as possible. 

@n3dwards can you provide your "Newspaper 8" theme *.zip to my email nsinelnikov.work@gmail.com ? It will be really helpful for the trying to works with this issue for fix.

Thanks for your patience and feedback! New version with fix (if it still does not work) will be released as soon as possible. I will be in touch in this "issue ticket".

**Comment by nikitasinelnikov** [comment] 2017-11-12 19:16
@uma-mantonio this video with active "Enfold" and UM2.0 (you can download it here https://github.com/ultimatemember/ultimatemember/archive/release/2.0.zip)

https://www.screencast.com/t/viGne40n

seems it works properly. Please provide more details if it does not work as it should.

!!!ATTENTION before install UM2.0 please create full backup of your site.

Thanks!

**Comment by nikitasinelnikov** [comment] 2017-11-14 11:09
@n3dwards thanks for theme's zip. I see the same issue in my install with Newspaper theme. It's quite conflicting hook for add fields to menus.....I will working for this fix, as soon as possible this issue will be fixed.

Thanks for your patience!

**Comment by nikitasinelnikov** [comment] 2017-12-14 16:23
Guys,

Sorry for delay....the latest commit https://github.com/ultimatemember/ultimatemember/commit/03082943af8fe4116c0d326a66551a2938d5eeed
will fix the issues with your menu's items

Thanks!

**Closed by nikitasinelnikov** 2017-12-14 16:23 UTC
Labels: 2.0, bug
